# Generated by Django 5.2.5 on 2025-08-24 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='core.cliente'),
        ),
    ]
