# Generated by Django 5.2.5 on 2025-09-07 23:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('Agendada', 'Agendada'), ('Concluida', 'Concluida'), ('Cancelada', 'Cancelada')], default='Agendada', max_length=15),
        ),
        migrations.AddField(
            model_name='consulta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
